Repository CEN3031-group16/GroupProject, pull requests merged in 2018-02, with the labels that each got.

#23 Document Test Plan - After Meeting Update
  Docs/Test Plan.docx
Labels: Documentation

#37 Flow chart
  Docs/ScrumblyFlowChart.vsdx
  Docs/ScrumblyUseCaseDiagram.vsdx
Labels: Documentation

#41 Resolve issues38 40
  source/Dialogs.py
  source/ScrumblesData.py
Labels: bug, enhancement

#59 LoginDBPatch Merge
  source/Scrumbles.py
  source/ScrumblesData.py
  source/ScrumblesDataTest.py
  source/loginView.py
  source/mainView.py
  source/masterView.py
Labels: Security

#63 Issue42 create item dialog
  source/Dialogs.py
  source/masterView.py
Labels: Feature

#84 Project queries -> Sprint 2
  source/Dialogs.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/backlogView.py
  source/masterView.py
Labels: Feature

#88 Issue 87 item edit
  source/Dialogs.py
  source/Scrumbles.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/backlogView.py
  source/masterView.py
Labels: Feature
