Repository CEN3031-group16/GroupProject, pull requests merged in 2018-03, with the labels that each got.

#86 Group project 85
  source/Dialogs.py
  source/masterView.py
Labels: enhancement

#100 Issue 79 change object creation
  .gitignore
  source/Dialogs.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/ScrumblesObjectsTest.py
  source/backlogView.py
  source/testing/ScrumblesDataTest.py
  source/testing/ScrumblesObjectsTest.py
  source/testing/ScrumblesObjectsTest_itemClass.py
  source/testing/ScrumblesObjectsTest_userClass.py
  source/testing/ScrumblesUnitTesting.py
  source/testing/SrcumblesObjectsTest.py
  source/testing/itemUnitTest.py
  source/testing/sprintUnitTest.py
  source/testing/test.py
  source/testing/testingRandomKeyGen.py
  source/testing/userUnitTest.py
Labels: enhancement

#103 Implement better update
  source/Dialogs.py
  source/Scrumbles.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/backlogView.py
  source/developerHomeView.py
  source/itemMangerView.py
  source/loginView.py
  source/mainView.py
  source/masterView.py
Labels: enhancement

#101 Remote updates
  serverScripts/mysqlport/mysqlportreporter.py
  serverScripts/mysqlport/threadServer.py
  serverScripts/mysqlportListen.sh
  serverScripts/readme.txt
  source/Dialogs.py
  source/Scrumbles.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/backlogView.py
  source/developerHomeView.py
  source/itemMangerView.py
  source/loginView.py
  source/mainView.py
  source/masterView.py
  source/remoteUpdate.py
  source/testing/getChangeUpdate.py
  source/testing/login.txt
  source/testing/testDataBlock.py
  source/testing/testDriveUpdater.py
Labels: enhancement

#106 SCardDescription
  source/ScrumblesFrames.py
  source/developerHomeView.py
Labels: Feature

#124 Impliment project to user relationship
  source/Dialogs.py
  source/ScrumblesData.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/developerHomeView.py
  source/masterView.py
Labels: Feature

#200 Resolve update issue by making a function that re points activeProjec…
  source/SDynamics.py
  source/SGraphs.py
  source/SLists.py
  source/ScrumblesFrames.py
  source/ScrumblesObjects.py
  source/developerHomeView.py
  source/masterView.py
  source/teamManagerView.py
Labels: bug

#205 Create Scrumbles Database SQL Script
  serverScripts/CreateScrumblesDB.sql
Labels: Feature

#207 Impliment epics issue154
  serverScripts/CreateScrumblesDB.sql
  source/DataBlock.py
  source/Dialogs.py
  source/Query.py
  source/SPopMenu.py
  source/Scrumbles.py
  source/ScrumblesData.py
  source/ScrumblesObjects.py
  source/backlogManagerView.py
  source/loginView.py
  source/masterView.py
  source/remoteUpdate.py
Labels: Epic, Feature, User Experience, bug, enhancement
