Repository CEN3031-group16/GroupProject, pull requests merged in 2018-04, with the labels that each got.

#210 Sanitze inputs
  source/DataBlock.py
  source/Dialogs.py
  source/Query.py
  source/SPopMenu.py
  source/ScrumblesData.py
  source/ScrumblesObjects.py
Labels: bug

#227 Comment Update + Developer Home View Layout
  source/SDynamics.py
  source/SGraphs.py
  source/SLists.py
  source/ScrumblesObjects.py
  source/developerHomeView.py
  source/itemManagerView.py
  source/masterView.py
  source/styling/styling.py
  source/teamManagerView.py
Labels: User Experience

#242 Scrolling comments
  source/SDynamics.py
Labels: enhancement

#263 Scrum Master can now assign users and approve items in Sprint View
  source/DataBlock.py
  source/masterView.py
  source/sprintManagerView.py
Labels: Feature

#280 Sprint delete
  source/DataBlock.py
  source/Query.py
  source/testing/testSprintDelete.py
Labels: bug

#305 The Rest of My Sprint 3 Issues
  .gitignore
  source/frames/SDynamics.py
  source/frames/SGraphs.py
  source/views/analyticsView.py
  source/views/developerHomeView.py
  source/views/mainView.py
  source/views/masterView.py
  source/views/teamManagerView.py
Labels: bug

#321 Little Fix for Tasks Graphing
  source/frames/SGraphs.py
  source/views/analyticsView.py
Labels: bug

#322 Dev Home User Backlog Fix
  source/views/developerHomeView.py
Labels: bug
